mysql:
  ip: mysql的ip
  port: mysql端口
  username: mysql用户名
  password: mysql密码
  database: mysql所操作的数据库
rabbitmq:
  ip: rabbitmq的ip
  port: rabbitmq的端口
  username: rabbitmq的用户名
  password: rabbitmq的密码
redis:
  ip: redis的ip
  port: redis的端口
  auth: redis的密码
minio:
  ip: minio的ip
  port: minio的端口
  access: minio的访问key
  secret: minio的密钥
email:
  host: 邮件提供者的地址
  username: 邮箱的发信人
  password: 收件人
  from: 邮箱的发信人
  auth:
    key: 访问发送邮件接口的key
    token: 访问发送邮件接口的token

# 使用方法, 完成本文件的配置, 生成config-prod.yml, 防止与本文相同的目录