mysql:
  ip: 192.168.99.100
  port: 20001
  username: root
  password: 1998
  database: BLOG
rabbitmq:
  ip: 192.168.99.100
  port: 20002
  username: guest
  password: guest
redis:
  ip: 192.168.99.100
  port: 20003
  auth: 1998
minio:
  ip: 192.168.99.100
  port: 20004
  access: a00000
  secret: Aa000000
email:
  host: smtp.qq.com
  username: 1938772251@qq.com
  password: zmpcbseybrddcdeh
  from: 1938772251@qq.com
  auth:
    key: A00000
    token: Aa.000000