server:
  port: 10002
spring:
  application:
    name: service-config-center
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  rabbitmq:
    host: rabbitmq.ip
    port: 20002
    username: guest
    password: guest
eureka:
  instance:
    hostname: service-config-center
  client:
    service-url:
      defaultZone: http://register.center.ip:10001/eureka
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'