server:
  port: 10002
spring:
  application:
    name: service-config-center
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  rabbitmq:
    host: 192.168.99.100
    port: 20002
    username: guest
    password: guest
eureka:
  instance:
    hostname: service-config-center
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'